### ISSUE TITLE
Add New Colour Scheme for Resumes

### ISSUE THREAD

**Issue by Saksham-13** [Saksham-13/ResumeMaker#1]
### Description
Currently, our resume maker app offers users a range of colour schemes to choose from when creating their resumes. However, we're looking to expand the available options to provide our users with more customization and style choices.

### Proposed Solution
This issue aims to introduce a new, visually appealing colour scheme for the resumes. The new colour scheme should harmonize with the existing design, providing a fresh and distinct look for users to select.

### Tasks
- [ ] Research and select a colour scheme that complements our app's overall design.
- [ ] Implement the selected colour scheme into the resume builder.

You can find the colour schemes by clicking the pick theme button

**Comment by maazshakeel** [comment]
Can I get assigned?

**Comment by Rhn14** [comment]
can i get assigned?

**Comment by Saksham-13** [comment]
> can i get assigned?

Yup, read the readme and get started

**Comment by Saksham-13** [comment]
You are currently assigned to Monopoly Issue hence am removing it, the issue is up for grabs right now

**Comment by sssai44** [comment]
Can u assign me this issue?

**Comment by PsychCodez** [comment]
can you assign me this issue

**Comment by samarth777** [comment]
can you assign me?

**Comment by nik2203** [comment]
Hi, could I be assigned to this issue please?

**Comment by Sadhana-24** [comment]
Can I get assigned?

**Comment by sid-nc** [comment]
can i get assigned

**Comment by Saksham-13** [comment]
> Can u assign me this issue?
> 

Yup

**Comment by Shriya285** [comment]
can I get assigned?

**Comment by uditreddys** [comment]
CAN I GET THIS ASSIGNED

**Comment by RisuKumari11** [comment]
can I get this issue

**Comment by komulannister** [comment]
can i get assigned to this?

**Comment by Suhaniverma2004** [comment]
can i get assigned?

**Comment by Aryamanseven** [comment]
pls assign

**Comment by SmritiMallya** [comment]
Can I get assigned?

**Comment by ananyashreyaz** [comment]
can I get assigned

**Comment by Shriya285** [comment]
can i get assigned?

**Comment by karun1763** [comment]
can i get assigned

**Comment by shreyahegde26** [comment]
can i get assigned to this please?

**Comment by Sidharth-k-2004** [comment]
can i be assigned #1

**Comment by saivihitha17** [comment]
i wanna be assigned

**Comment by N0Xl0US** [comment]
can i get assigned

**Comment by BhavikaPradeep** [comment]
can i get assigned pleaseeee please

**Comment by harveen-10** [comment]
can i get assigned to this issue?

**Comment by 7Akshu77** [comment]
Can I get assigned to the issue

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by shreyahegde26** [comment]
can i get assigned to this???please??

**Comment by nishanthjmodpur** [comment]
can i get assigned?

**Comment by Shriya285** [comment]
can i get assigned?
